---
- name: Reboot master nodes
  network.offline_migration_sdn_to_ovnk.reboot_nodes:
    role: "master"
    namespace: "openshift-machine-config-operator"
    daemonset_label: "machine-config-daemon"
    delay: 1
    retries: 5
    retry_delay: 3
    timeout: "{{ reboot_timeout_to_retry_oc_wait | default(1800) }}"
    oc_wait_timeout: "{{ reboot_wait_timeout_node_ready | default(120) }}"

- name: Reboot worker nodes
  network.offline_migration_sdn_to_ovnk.reboot_nodes:
    role: "worker"
    namespace: "openshift-machine-config-operator"
    daemonset_label: "machine-config-daemon"
    delay: 1
    retries: 5
    retry_delay: 3
    timeout: "{{ reboot_timeout_to_retry_oc_wait | default(1800) }}"
    oc_wait_timeout: "{{ reboot_wait_timeout_node_ready | default(120) }}"
